### PR TITLE
#313 Markdown doesn't work in widget mode

### LINKED ISSUE #313: Markdown doesn't work in widget mode ...
the widgets don't show the correct formatting, they show the markdown tags. Is this feature planned ?

Thank you

### PR DESCRIPTION
**Pull request by stefan-niedermann**
Fixes #313. Please review @dan0xii 

device-2018-08-29-091218

### CODE REVIEW

File: app/src/main/java/it/niedermann/owncloud/notes/android/appwidget/SingleNoteWidgetFactory.java [hunk 1]
```diff
@@ -6,17 +6,25 @@
 import android.content.SharedPreferences;
 import android.os.Bundle;
 import android.preference.PreferenceManager;
+import android.text.Spannable;
+import android.text.SpannableString;
+import android.text.style.StyleSpan;
```
Comment (korelstar) [inline app/src/main/java/it/niedermann/owncloud/notes/android/appwidget/SingleNoteWidgetFactory.java]: These three imports seem to be unused and should be removed.

Comment (stefan-niedermann) [reply app/src/main/java/it/niedermann/owncloud/notes/android/appwidget/SingleNoteWidgetFactory.java]: Fixed in 78580addf1da55dea7f2215de57f0322df5a6566

**Comment by dan0xii** [comment]
Looks really good and I don't see any issues with the code.
