### PR TITLE
Fix #679 Lots of empty notes are created if the server is full

### LINKED ISSUE #679: Lots of empty notes are created if the server is full
**Describe the bug**
I recently tried to create a new note while my Nextcloud server was full. Every time the app tried to sync, dozens of empty notes were added. The problem disappeared once I cleared some space from my Nextcloud server. 

I don't know if it is relevant but I don't have my own server, I have an account with limited storage from a 3rd party provider. 

**To Reproduce**
1. Log in to an account with no space left
2. Create a new note and sync it. 

**Server**
 - Nextcloud-Version: 17.0.0.9
 - Nextcloud Notes-Version (server app): unknown 
 - PHP-Version: unknown

**Smartphone (please complete the following information):**
- Device: Sony Xperia x compact 
 - Android-Version: 8.0.0

### PR DESCRIPTION
**Pull request by stefan-niedermann**
Fixes #679 

Signed-off-by: stefan-niedermann <info@niedermann.it>

### CODE REVIEW

File: app/src/main/java/it/niedermann/owncloud/notes/persistence/NoteServerSyncHelper.java [hunk 1]
```diff
@@ -364,13 +367,21 @@ private void pushLocalChanges() {
                 } catch (NextcloudHttpRequestFailedException e) {
                     if (e.getStatusCode() == 304) {
                         Log.d(TAG, "Server returned HTTP Status Code 304 - Not Modified");
+                        return LoginStatus.OK;
```
Comment (korelstar) [inline app/src/main/java/it/niedermann/owncloud/notes/persistence/NoteServerSyncHelper.java]: What happens if there where multiple changes? `db.getLocalModifiedNotes` will return multiple notes and the for-loop is executed multiple times. However, in some cases, the execution is cancelled due to these new return statements. This means, all local changes that are behind a local change with error will not be executed.

An interesting use case is if the storage is full. I change a note and see the error message. Then I want to delete old notes in order to free some storage. However, the deletion will never be executed, since `pushLocalChanges` is cancelled after the first error.

**Comment by stefan-niedermann** [comment]
You are totally right. What do you propose? Make a `LoginStatus`-variable outside of the `for`-loop with default value `OK` and assign another value in error case?

Of course each iteration could theoretically produce still different errors and this would only allow one to see the very last message. But then a user could work on one error after another.

Thank you for your review btw :)

**Comment by korelstar** [comment]
That approach would be better. Although it wouldn't show all different errors, I think that would be fine.

Another option would be to build a `Set<LoginStatus>` and to add every status which is not `LoginStatus.OK`. Later, a string could be builded by mapping the elements to their error message and concatenate them together. But that could be confuse the user.

**Comment by stefan-niedermann** [comment]
:laughing: i really would be so mad if i would like to sync a bunch of notes and then immediately would receive a toast (!) which covers the whole screen and contains 7 error messages :laughing: 

No, indeed i think it's actually a feature to display only one error message at the time.

Will rewrite this part and adjust to what we discussed.

**Comment by stefan-niedermann** [comment]
Have a look at #721
